"""add_oauth_columns

Revision ID: f94a2e1cbf18
Revises: 1d10633a24e3
Create Date: 2026-03-30 13:43:56.801547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94a2e1cbf18'
down_revision: Union[str, None] = '1d10633a24e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_sub', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('oauth_sub')
        batch_op.drop_column('oauth_provider')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('icon_id')

    # ### end Alembic commands ###
